name       : ca-certs
version    : '20230624'
release    : 42
source     :
    - https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt : c47475103fb05bb562bbadff0d1e72346b03236154e1448a6ca191b740f83507
    - https://raw.githubusercontent.com/agl/extract-nss-root-certs/492d8c9/convert_mozilla_certdata.go : 30afd0ca1df9b7788b830485645c4a2f72b07c1c9eb5c66941ae3d0b87e9e623
license    :
    - Apache-2.0 # Conversion script
    - MPL-2.0    # Actual cert file
component  : system.base
summary    : Certificate Authority Files
description: |
    The Public Key Inrastructure is used for many security issues in a Linux system. In order for a certificate to be trusted, it must be signed by a trusted agent called a Certificate Authority (CA).
extract    : no
builddeps  :
    - golang
setup      : |
    ln -s $sources/* $workdir
build      : |
    go run convert_mozilla_certdata.go --to-files

    # The bundle generation could be a usysconf trigger in future.
    cat *.pem > ca-certificates.crt
install    : |
    install -Dm00644 *.pem ca-certificates.crt -t $installdir/etc/ssl/certs
